name: Add package comment on a pull request
# Based on work from https://github.com/orgs/community/discussions/51403#discussioncomment-5535167
on:
  workflow_run:
    types:
      - completed
    workflows:
      - 'Creating plugin package in the PR'

jobs:
  comment:
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: Download workflow artifact
        uses: dawidd6/action-download-artifact@v2.11.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: peek_icons.yml
          run_id: ${{ github.event.workflow_run.id }}

      - name: Read the pr_num file
        id: pr_number_reader
        uses: juliangruber/read-file-action@v1.0.0
        with:
          path: ./pr_number/pr_number.txt

      - name: Get Artifact and Pull request info
        env:
          GITHUB_TOKEN: ${{ github.token }}
          WORKFLOW_RUN_EVENT_OBJ: ${{ toJSON(github.event.workflow_run) }}
          WORKFLOW_RUN_EVENT_OBJ_2: ${{ toJSON(github.event.pull_request) }}
          WORKFLOW_RUN_EVENT_OBJ_3: ${{ toJSON(github.event) }}
          OWNER: ${{ github.repository_owner }}
          REPO: ${{ github.event.repository.name }}
          PULL_REQUEST_EVENT_NUMBER: ${{ steps.pr_number_reader.outputs.content }}
        run: |
          PREVIOUS_JOB_ID=$(jq -r '.id' <<< "$WORKFLOW_RUN_EVENT_OBJ")
          echo "Previous Job ID: $PREVIOUS_JOB_ID"
          echo "PREVIOUS_JOB_ID=$PREVIOUS_JOB_ID" >> "$GITHUB_ENV"
          
          echo "Workflow run : $WORKFLOW_RUN_EVENT_OBJ"
          echo "Workflow run 2: $WORKFLOW_RUN_EVENT_OBJ_2"
          echo "Workflow run 3: $WORKFLOW_RUN_EVENT_OBJ_3"
          
          SUITE_ID=$(jq -r '.check_suite_id' <<< "$WORKFLOW_RUN_EVENT_OBJ")
          echo "Previous Suite ID: $SUITE_ID"
          echo "SUITE_ID=$SUITE_ID" >> "$GITHUB_ENV"
          
          ARTIFACT_ID=$(gh api "/repos/$OWNER/$REPO/actions/artifacts" \
            --jq ".artifacts.[] |
            select(.workflow_run.id==${PREVIOUS_JOB_ID}) |
            select(.expired==false) |
            .id")
          
          echo "Artifact ID: $ARTIFACT_ID"
          echo "ARTIFACT_ID=$ARTIFACT_ID" >> "$GITHUB_ENV"
          
          PR_NUMBER=$(jq -r '.pull_requests[0].number' \
            <<< "$WORKFLOW_RUN_EVENT_OBJ")
          
          echo "Pull request Number: PULL_REQUEST_EVENT_NUMBER"
          echo "PR_NUMBER=PULL_REQUEST_EVENT_NUMBER" >> "$GITHUB_ENV"
          
          echo "Pull request event number :$PULL_REQUEST_EVENT_NUMBER"
          
          HEAD_SHA=$(jq -r '.pull_requests[0].head.sha' \
            <<< "$WORKFLOW_RUN_EVENT_OBJ")
          
          echo "Head SHA: $HEAD_SHA"
          echo "HEAD_SHA=$HEAD_SHA" >> "$GITHUB_ENV"
      - name: Find Comment
        uses: peter-evans/find-comment@v2
        id: find-comment
        with:
          issue-number: ${{ github.event.issue.number }}
          comment-author: 'github-actions[bot]'
      - name: Update Comment
        env:
          JOB_PATH: "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ env.PREVIOUS_JOB_ID }}"
          ARTIFACT_URL: "${{ github.server_url }}/${{ github.repository }}/suites/${{ env.SUITE_ID }}/artifacts/${{ env.ARTIFACT_ID }}"
          HEAD_SHA: "${{ env.HEAD_SHA }}"
        uses: peter-evans/create-or-update-comment@v3
        with:
          token: ${{ github.token }}
          issue-number: ${{ env.PR_NUMBER }}
          comment-id: ${{ steps.find-comment.outputs.comment-id }}
          edit-mode: replace
          body: |-
            ![badge]
            
            Plugin zip package for the changes in this PR has been successfully built!.
            
            Download the plugin zip file here ${{ env.ARTIFACT_URL }}
            
            [badge]: https://img.shields.io/badge/package_build-success-green
